name: Deploy to Amazon ECS

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  
jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: configure-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1        

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t 695292474035.dkr.ecr.us-east-1.amazonaws.com/github-actions-nginx:latest . 
        docker push 695292474035.dkr.ecr.us-east-1.amazonaws.com/github-actions-nginx:latest
        
        echo "::set-output name=image::695292474035.dkr.ecr.us-east-1.amazonaws.com/github-actions-nginx:latest"
        
    - name: Download task definition
      id: task-def
      run: |
        aws ecs describe-task-definition --task-definition github-actions-nginx --query taskDefinition > task-definition.json
        
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json
        service: nginx
        cluster: github-actions-test
        wait-for-service-stability: false
